# Generated by Django 3.0.5 on 2020-05-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Particulars', models.CharField(max_length=1200)),
                ('Units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GoldRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Rate', models.DecimalField()),
                ('ParticularsId', models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='appapi.GoldMaster')),
            ],
        ),
    ]
