# Generated by Django 3.0.5 on 2020-05-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldrates',
            name='Rate',
            field=models.FloatField(),
        ),
    ]
