# Generated by Django 3.0.5 on 2020-05-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0003_auto_20200504_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldrates',
            name='Rate',
            field=models.DecimalField(decimal_places=2, max_digits='20'),
        ),
    ]
