# Generated by Django 3.0.5 on 2020-05-04 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0004_auto_20200504_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldrates',
            name='ParticularsId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golddetails', to='appapi.GoldMaster'),
        ),
    ]
