# Generated by Django 3.0.5 on 2020-05-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0005_auto_20200504_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldrates',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
