# Generated by Django 3.0.5 on 2020-05-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0006_auto_20200504_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldrates',
            name='date',
            field=models.DateField(),
        ),
    ]
