# Generated by Django 3.0.5 on 2020-05-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0007_auto_20200504_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldrates',
            name='Rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='goldrates',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
